# This workflow builds the game every time a PR is opened.
# It will fail the build if it fails to compile
# And also triggers a separate workflow to deploy a preview copy of the build
# (which needs to be a separate run for security reasons.
# see https://securitylab.github.com/research/github-actions-preventing-pwn-requests/ for context)

name: Build PR

on:
  pull_request:
    paths: 
      - 'scenes/**'
      - 'scripts/**'
      - 'sfx/**'
      - 'sprites/**'
      - 'ui/**'
      - export_presets.cfg
      - .project.godot

jobs:
  build_game:
    runs-on: ubuntu-latest
    steps:
      - name: checkout latest code
        uses: actions/checkout@v2.3.1
      - name: update credits
        run: |
          git shortlog --summary HEAD |sed -E 's/\s*[0-9]+\s+//g' >credits.txt
      - name: export with Godot Engine and release on GitHub
        uses: firebelley/godot-export@v3.0.0
        with:
          create_release: false
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4.4/Godot_v3.4.4-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4.4/Godot_v3.4.4-stable_export_templates.tpz
          relative_export_path: ./
          relative_project_path: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # The next workflow needs access to the PR number to comment on it
      # This is the best way we have to thread that through, sigh.
      # Shoving it into HTML5 lets us upload a single artifact instead of juggling 2
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > ./HTML5/pr_number

      - uses: actions/upload-artifact@v3
        with:
          name: pr
          path: HTML5
